/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Frieren.glb 
*/

import React, { useEffect } from "react";
import { useGLTF, Wireframe } from "@react-three/drei";
import { useStore } from "../Store.jsx";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Frieren.glb");
  const isWireframe = useStore((state) => state.isWireframe);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.EyesHighlight.geometry}
        material={materials.M_Highlight}
        wireframe
      />
      <mesh
        geometry={nodes.HairTailHighlight.geometry}
        material={materials.Master_Hair}
      />
      <mesh
        geometry={nodes.HairSideHighlight.geometry}
        material={materials.Master_Hair}
      />
      <mesh
        geometry={nodes.Eyeshade.geometry}
        material={materials.EyeOcclusion}
      />
      <mesh geometry={nodes.IrisL.geometry} material={materials.M_Eyes} />
      <mesh geometry={nodes.IrisR.geometry} material={materials.M_Eyes} />
      <mesh
        geometry={nodes.Clothes.geometry}
        material={materials.Master_Clothes}
      />
      <mesh
        geometry={nodes.Earring.geometry}
        material={materials.Master_Head}
      />
      <mesh
        geometry={nodes.Eyebrows.geometry}
        material={materials.Master_Head}
      />
      <mesh
        geometry={nodes.Eyelashes.geometry}
        material={materials.M_Eyeline}
      />
      <mesh
        geometry={nodes.HairFront001.geometry}
        material={materials.Master_Hair}
      />
      <mesh
        geometry={nodes.HairSide001.geometry}
        material={materials.Master_Hair}
      />
      <mesh
        geometry={nodes.HairTail001.geometry}
        material={materials.Master_Hair}
      />
      <mesh
        geometry={nodes.Pants001.geometry}
        material={materials.Master_Clothes}
      />
      <mesh
        geometry={nodes.Ribbon.geometry}
        material={materials.Master_Clothes}
      />
      <mesh geometry={nodes.Scalp.geometry} material={materials.Master_Hair} />
      <mesh geometry={nodes.Teeth.geometry} material={materials.Master_Head} />
      <mesh geometry={nodes.Tongue.geometry} material={materials.Master_Head} />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials.Master_Head}
      />
      <mesh
        geometry={nodes.Cube002_1.geometry}
        material={materials.Master_Body}
      >
        {isWireframe && (
          <mesh geometry={nodes.Cube002_1.geometry}>
            <meshBasicMaterial
              wireframe={true}
              color="#00ffcc" // Bebas pilih warna! Cyan/Neon Green sangat cocok
              /* Trik Anti-Flicker (Z-Fighting) */
              polygonOffset={true}
              polygonOffsetFactor={-1}
              polygonOffsetUnits={-1}
            />
          </mesh>
        )}
      </mesh>
      <mesh
        geometry={nodes.Cube002_2.geometry}
        material={materials.Master_Face}
      />
      <mesh geometry={nodes.Cube002_3.geometry} material={materials.M_Sklera} />
    </group>
  );
}

useGLTF.preload("/Frieren.glb");
